/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lead {
  'id' : string,
  'propertyType' : PropertyType,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
  'phone' : string,
  'budget' : bigint,
}
export interface Property {
  'id' : string,
  'features' : Array<string>,
  'propertyType' : PropertyType,
  'bedrooms' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'sqft' : bigint,
  'imageUrl' : string,
  'category' : PropertyCategory,
  'price' : bigint,
  'location' : string,
}
export type PropertyCategory = { 'featured' : null } |
  { 'land' : null };
export type PropertyType = { 'commercial' : null } |
  { 'villa' : null } |
  { 'penthouse' : null } |
  { 'land' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLead' : ActorMethod<
    [string, string, string, bigint, PropertyType, string],
    undefined
  >,
  'createProperty' : ActorMethod<[Property], undefined>,
  'deleteProperty' : ActorMethod<[string], undefined>,
  'getAllProperties' : ActorMethod<[], Array<Property>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getPropertiesByCategory' : ActorMethod<[PropertyCategory], Array<Property>>,
  'getPropertiesByType' : ActorMethod<[PropertyType], Array<Property>>,
  'getProperty' : ActorMethod<[string], [] | [Property]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProperty' : ActorMethod<[string, Property], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];