/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'villa' : IDL.Null,
  'penthouse' : IDL.Null,
  'land' : IDL.Null,
});
export const PropertyCategory = IDL.Variant({
  'featured' : IDL.Null,
  'land' : IDL.Null,
});
export const Property = IDL.Record({
  'id' : IDL.Text,
  'features' : IDL.Vec(IDL.Text),
  'propertyType' : PropertyType,
  'bedrooms' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'sqft' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : PropertyCategory,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'propertyType' : PropertyType,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'budget' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, PropertyType, IDL.Text],
      [],
      [],
    ),
  'createProperty' : IDL.Func([Property], [], []),
  'deleteProperty' : IDL.Func([IDL.Text], [], []),
  'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getPropertiesByCategory' : IDL.Func(
      [PropertyCategory],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getPropertiesByType' : IDL.Func(
      [PropertyType],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getProperty' : IDL.Func([IDL.Text], [IDL.Opt(Property)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProperty' : IDL.Func([IDL.Text, Property], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'villa' : IDL.Null,
    'penthouse' : IDL.Null,
    'land' : IDL.Null,
  });
  const PropertyCategory = IDL.Variant({
    'featured' : IDL.Null,
    'land' : IDL.Null,
  });
  const Property = IDL.Record({
    'id' : IDL.Text,
    'features' : IDL.Vec(IDL.Text),
    'propertyType' : PropertyType,
    'bedrooms' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'sqft' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : PropertyCategory,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'propertyType' : PropertyType,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'budget' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, PropertyType, IDL.Text],
        [],
        [],
      ),
    'createProperty' : IDL.Func([Property], [], []),
    'deleteProperty' : IDL.Func([IDL.Text], [], []),
    'getAllProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getPropertiesByCategory' : IDL.Func(
        [PropertyCategory],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getPropertiesByType' : IDL.Func(
        [PropertyType],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getProperty' : IDL.Func([IDL.Text], [IDL.Opt(Property)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProperty' : IDL.Func([IDL.Text, Property], [], []),
  });
};

export const init = ({ IDL }) => { return []; };